# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

vars:
  # Frequently changed
  SERVICES: mysql mariadb isucondition.rust
  SRC_DIR: "/home/isucon/webapp/rust"
  REPO_DIR: /home/isucon/repo
  LOGS: /var/log/mysql/mysql-slow.log /var/log/nginx/access.log

  # Rarely changed

tasks:
  ####################
  #      Deploy      #
  ####################
  deploy:
    desc: Deploy the latest configuration
    deps:
      - checkout
    cmds:
      - task: build
      - sudo systemctl daemon-reload
      - task: restart-all
      - task: truncate-log

  build:
    desc: Build the application
    dir: "{{.SRC_DIR}}"
    cmds:
      - cargo build --release

  ####################
  #     Utility      #
  ####################
  analyze:
    desc: Run alp and slp
    deps:
      - run-alp
      - run-slp

  truncate-log:
    desc: Truncate log files
    cmds:
      - sudo truncate -s 0 {{.LOGS}}

  checkout:
    desc: Checkout and sync with the latest remote branch
    vars:
      BRANCH: '{{.CLI_ARGS | default "main"}}'
    dir: "{{.REPO_DIR}}"
    cmds:
      - git fetch --all
      - git reset --hard origin/{{.BRANCH}}
      - git switch -C {{.BRANCH}} origin/{{.BRANCH}}

  enable:
    desc: Enable and start specified services
    cmds:
      - sudo systemctl enable --now {{.CLI_ARGS}}

  disable:
    desc: Disable and stop specified services
    cmds:
      - sudo systemctl disable --now {{.CLI_ARGS}}

  status:
    desc: Show status of specified services
    cmds:
      - sudo systemctl status {{.CLI_ARGS}}

  status-all:
    desc: Show status of all services related to the application
    cmds:
      - sudo systemctl status {{.SERVICES}}

  restart:
    desc: Restart specified services
    cmds:
      - sudo systemctl restart {{.CLI_ARGS}}

  restart-all:
    desc: Restart all services related to the application
    cmds:
      - sudo systemctl restart {{.SERVICES}}

  reload-sysctl:
    desc: Reload sysctl configuration
    cmds:
      - sudo sysctl -p

  ####################
  #     Internal     #
  ####################
  run-alp:
    cmds:
      - touch /tmp/alp.log && mv /tmp/alp.log "/tmp/alp.log.$(date +%Y%m%d-%H%M%S)"
      - alp ltsv --config "{{.REPO_DIR}}/config/alp.yml" --file /var/log/nginx/access.log > "/tmp/alp.log"

  run-slp:
    cmds:
      - touch /tmp/slp.log && mv /tmp/slp.log "/tmp/slp.log.$(date +%Y%m%d-%H%M%S)"
      - slp my --config "{{.REPO_DIR}}/config/slp.yml" --file /var/log/mysql/mysql-slow.log > /tmp/slp.log
