matching_groups:
  - ^/isu/[^/]+$
  - ^/api/isu/[^/]+$
  - ^/api/isu/[^/]+/condition$
  - ^/api/isu/[^/]+/graph$
  - ^/api/isu/[^/]+/icon$
  - ^/assets/[^/]+$
sort: sum
reverse: true
output: count,2xx,3xx,4xx,5xx,method,uri,sum,avg,p50,p90,p99,max_body
percentiles: [50, 90, 99]
